class Images {
  static const String logo = "assets/images/logo.png";
  static const String svgsplashLogo = "assets/icons/splash.svg";
  static const String splashLogo = "assets/images/splashLogo.png";
  static const String placeholder = "assets/images/placeholder.png";
  // static const String google = "assets/images/google.png";
  // static const String apple = "assets/images/apple.png";
  // static const String terms = "assets/images/terms.png";
  // static const String privacy = "assets/images/privacy.png";
  // static const String support = "assets/images/support.png";
  static const String logout = "assets/images/logout.png";
  static const String svgPhoneFieldLogo = "assets/icons/phoneField.svg";
  static const String arrowForward = "assets/images/arrow_forward.png";
  static const String companiesIcon = "assets/images/companiesIcon.png";
  static const String svgSearch = "assets/icons/search.svg";
  static const String svgBell = "assets/icons/bell.svg";
  static const String svgBriefcase = "assets/icons/briefcase.svg";
  static const String svgShoppingBag = "assets/icons/shopping-bag.svg";
  static const String svgTenders = "assets/icons/tenders.svg";
  static const String svgHeart = "assets/icons/heart.svg";
  static const String svgHeartBorder = "assets/icons/heart_border.svg";
  static const String svgMap = "assets/icons/map.svg";
  static const String svgArrowForwardIcon = "assets/icons/arrowForwardIcon.svg";
  static const String svgPlus = "assets/icons/plus.svg";
  static const String svgArrowUpDown = "assets/icons/arrows-down-up.svg";
  static const String svgArrowRight = "assets/icons/arrow_right.svg";
  static const String svgCompanies = "assets/icons/companies.svg";
  static const String svgTrash = "assets/icons/trash.svg";
  static const String svgLogout = "assets/icons/log-out.svg";
  static const String svgFileText = "assets/icons/file-text.svg";
  static const String svgMail = "assets/icons/mail.svg";
  static const String svgFlag = "assets/icons/flag.svg";
  static const String svgBoxIcon1 = "assets/icons/logoutBoxIcon.svg";
  static const String svgBoxIcon2 = "assets/icons/trashBoxIcon.svg";
  static const String svgHelpCircle = "assets/icons/help-circle.svg";
  static const String svgAlertCircle = "assets/icons/alert-circle.svg";
  static const String svgDownload = "assets/icons/download.svg";
  static const String svgVerified = "assets/icons/verified_icon.svg";
  static const String svgCreditCard = "assets/icons/credit-card.svg";
  static const String svgWallet = "assets/icons/wallet.svg";
  static const String svgSendArrow = "assets/icons/send.svg";
  static const String svgFile = "assets/icons/file.svg";
  static const String svgMailIcon = "assets/icons/mail-icon.svg";
  static const String svgDocument = "assets/icons/document.svg";
  static const String svgCompanyReviews = "assets/icons/company_reviews.svg";

  // images used
  static const String emptySvg = "";
  static const String filter = "assets/icons/Filters_lines.svg";
  static const String svgHome = "assets/icons/home.svg";
  static const String svgCategory = "assets/icons/grid.svg";
  static const String svgList = "assets/icons/list.svg";
  static const String svgChat = "assets/icons/message-square.svg";
  static const String svgProfile = "assets/icons/user.svg";
  static const String svgUser = "assets/icons/user_icon.svg";
  static const String svgLocation1 = "assets/icons/map.svg"; // duplicate
  static const String dollarSignSvg = "";
  static const String calenderSvg = "";
  static const String svgStarFill = "";
  static const String svgAlert = "assets/icons/alert-triangle.svg";
  static const String done = "assets/icons/sucess_check.svg";
  static const String svgArrowForward = "assets/icons/arrowForwardIcon.svg";
  static const String whatsappFillSvg = "";
  static const String telegramSvg = "";
  static const String instagramSvg = "";
  static const String vkSvg = "";
  static const String gmailSvg = "";
  static const String globeSvg = "";
  static const String whatsappSvg = "";
  static const String phoneFieldLogo = "";
  static const String svgLock = "assets/images/lock.png";
  static const String language = "assets/images/language.png";

  // png
  static const String uploadImagePng = "assets/images/upload-image.png";
  static const String imagePng = "assets/images/image.png";
}
